apiVersion: v1
kind: Service
metadata:
  name: {{ include "emailservice.fullname" . }}
  labels:
    {{- include "emailservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "emailservice.selectorLabels" . | nindent 4 }}